# Generated by Django 3.2.8 on 2022-09-27 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0003_auto_20220927_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(max_length=64)),
                ('nickName', models.CharField(max_length=256)),
                ('realName', models.CharField(max_length=64)),
                ('phoneNum', models.CharField(max_length=64, null=True)),
                ('isEmployee', models.BooleanField(default=False, null=True)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2022, 9, 27, 2, 59, 28, 372659))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2022, 9, 27, 2, 59, 28, 372777))),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 2, 59, 28, 371786)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 2, 59, 28, 371856)),
        ),
    ]
