# Generated by Django 3.2.8 on 2022-09-27 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0004_auto_20220927_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 41, 7, 331461))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 41, 7, 331478))),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 41, 7, 330257)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 41, 7, 330285)),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 41, 7, 330760)),
        ),
    ]
