# Generated by Django 3.2.8 on 2022-09-27 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0005_auto_20220927_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 41, 26, 761725)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 41, 26, 761254)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 41, 26, 761280)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 41, 26, 762491)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 41, 26, 762509)),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 41, 26, 761708)),
        ),
    ]
