# Generated by Django 3.2.8 on 2022-09-27 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0008_auto_20220927_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 50, 30, 63055)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 50, 30, 63099)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 50, 30, 64481)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 50, 30, 64499)),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 50, 30, 63713)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 50, 30, 63729)),
        ),
    ]
