# Generated by Django 3.2.8 on 2022-09-28 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0014_auto_20220928_0228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counters',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 5, 7, 4, 913182)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 5, 7, 4, 913200)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wxcloudrun.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 5, 7, 4, 912065)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 5, 7, 4, 912112)),
        ),
    ]
