# Generated by Django 3.2.8 on 2022-09-28 05:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0015_auto_20220928_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 5, 8, 27, 816363)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wxcloudrun.roles'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 5, 8, 27, 816379)),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 5, 8, 27, 815344)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 5, 8, 27, 815374)),
        ),
    ]
