# Generated by Django 3.2.8 on 2022-10-03 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0019_auto_20221002_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkedIn24Hours', models.BooleanField(default=False)),
                ('startTemperature', models.IntegerField(null=True)),
                ('endTemperature', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wxcloudrun.users')),
            ],
            options={
                'db_table': 'Covids',
            },
        ),
    ]
