# Generated by Django 3.2.8 on 2022-10-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0020_covids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covids',
            name='endTemperature',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='covids',
            name='startTemperature',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
